name: Deploy Nuxt.Js to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Nuxt.Js to VPS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy Application
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USER }}
              run: |
                  ssh $SSH_USER@$SSH_HOST << 'EOF'
                    # Load environment variables
                    source ~/.profile
                    source ~/.bashrc

                    # Navigate to the project directory
                    cd /root/www/pemira-client

                    # Pull the latest code
                    git pull

                    # Install dependencies and build the project
                    npm install --production
                    npm run build

                    # Restart the application using PM2
                    pm2 restart pemira-client || pm2 start npm --name "pemira-client" -- run start
                  EOF
