name: Deploy Nuxt.js to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Nuxt.js to VPS
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Set up SSH
              run: |
                  # Menyiapkan konfigurasi SSH untuk akses ke VPS
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}

            - name: Deploy Application to VPS
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  DEPLOY_DIR: /var/www/my-nuxt-app
              run: |
                  # Menjalankan perintah di VPS via SSH
                  echo "Deploying to VPS..."
                  ssh $SSH_USER@$SSH_HOST << 'EOF'
                    set -e  # Menyebabkan skrip berhenti jika ada perintah yang gagal

                    # Menampilkan versi Node.js dan npm di VPS untuk debugging
                    node -v
                    npm -v

                    # Menambahkan path npm dan pm2 jika perlu
                    export PATH=$PATH:/usr/local/bin

                    # Pindah ke direktori aplikasi
                    cd $DEPLOY_DIR

                    # Menarik perubahan terbaru dari GitHub
                    echo "Pulling latest changes from GitHub..."
                    git pull origin main

                    # Install dependensi aplikasi
                    echo "Installing dependencies..."
                    npm install --production  # Menggunakan flag --production untuk hanya menginstal dependensi produksi

                    # Build aplikasi Nuxt.js
                    echo "Building Nuxt.js application..."
                    npm run build

                    # Restart aplikasi menggunakan PM2
                    echo "Restarting application with PM2..."
                    pm2 restart nuxt-app || pm2 start npm --name 'nuxt-app' -- run start

                    echo "Deployment completed successfully."
                  EOF
