name: Deploy Nuxt.Js to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Nuxt.Js to VPS
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout kode dari GitHub
            - name: Checkout Code
              uses: actions/checkout@v2

            # 2. Setup SSH untuk koneksi ke VPS
            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            # 3. Deploy aplikasi ke VPS
            - name: Deploy Application
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USER }}
              run: |
                  ssh $SSH_USER@$SSH_HOST << 'EOF'
                    bash -l -c "
                      # Menambahkan path npm dan pm2 ke environment shell
                      export PATH=$PATH:/usr/local/bin

                      # Pindah ke direktori proyek
                      cd /root/www/pemira-client

                      # Tarik perubahan terbaru dari GitHub
                      git pull

                      # Install dependensi (menggunakan semua dependensi, termasuk devDependencies untuk build)
                      npm install

                      # Build proyek
                      npm run build

                      # Restart aplikasi menggunakan PM2
                      pm2 restart pemira-client || pm2 start npm --name 'pemira-client' -- run start
                    "
                  EOF
